version: "3.5"

services:
  database:
    image: postgis/postgis:15-3.4
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
